### ISSUE TITLE
 Freeze arrow breaks

### ISSUE THREAD

**Issue by tomo39** [SpottyMatt/raspian-3b-stepmania-arcade#13]
Matt like Hello
Enjoying and using stepmania arcade on raspberry pi4
But when you play using the "numeric keypad"
Sometimes freeze arrows break

This did not happen with my previous raspberry pi3 SM5.0
Please tell me how to install 5.0

**Comment by SpottyMatt** [comment]
> **Notes > StepMania Version**
> _By default, if stepmania is not present on your Pi's $PATH this will install a pre-compiled StepMania binary from raspbian-stepmania-deb.
>
> _If you want to set up a different version of StepMania as an arcade console (with no guarantees that these scripts will work with your chosen version), just make sure that version is installed and on your $PATH before running make._
> -- https://github.com/SpottyMatt/raspbian-stepmania-arcade#stepmania-version

If you _uninstall_ the `stepmania` package that was installed by the arcade setup, and then _build_ StepMania 5.0 from source with these instructions: https://github.com/SpottyMatt/raspbian-stepmania-build (Be sure to [change the source directory to the 5.0 commit that you want](https://github.com/SpottyMatt/raspbian-stepmania-build#stepmania-source)!)

... then install the arcade again, you should find that the arcade is configured for your StepMania 5.0.

You will need to provide the `SM_INSTALL_DIR` and `SM_CONFIG_DIR` environment variables listed in the "StepMania Arcade > Notes > StepMania Version" section when installing the arcade a second time. Make sure that they point to the correct StepMania 5.0 folders.

I'm sorry I don't have a step-by-step recipe for this at the moment; you'll have to do some figuring and thinking. However, I promise that the _process_ works, because the StepMania arcade originally used StepMania-5.2 instead of 5.1. You can definitely point it at StepMania 5.0.

I don't know if the "extras" like the AutoStart, auto-configuration, and support for multiple controllers will work with 5.0, though. It probably will; I just have never tested it.
